package cmd

var extDisplay = map[string]string{
	".go":     "Go",
	".py":     "Python",
	".java":   "Java",
	".rs":     "Rust",
	".c":      "C",
	".cpp":    "C++",
	".h":      "C Header",
	".hpp":    "C++ Header",
	".rb":     "Ruby",
	".php":    "PHP",
	".swift":  "Swift",
	".kt":     "Kotlin",
	".dart":   "Dart",
	".lua":    "Lua",
	".r":      "R",
	".jl":     "Julia",
	".zig":    "Zig",
	".nim":    "Nim",
	".cr":     "Crystal",
	".ex":     "Elixir",
	".exs":    "Elixir Script",
	".erl":    "Erlang",
	".hs":     "Haskell",
	".clj":    "Clojure",
	".scala":  "Scala",
	".groovy": "Groovy",

	".js":     "JavaScript",
	".ts":     "TypeScript",
	".jsx":    "React JSX",
	".tsx":    "React TSX",
	".html":   "HTML",
	".htm":    "HTML",
	".css":    "CSS",
	".scss":   "SCSS",
	".sass":   "SASS",
	".less":   "Less",
	".vue":    "Vue",
	".svelte": "Svelte",

	".json":     "JSON",
	".yaml":     "YAML",
	".yml":      "YAML",
	".toml":     "TOML",
	".xml":      "XML",
	".md":       "Markdown",
	".markdown": "Markdown",
	".sql":      "SQL",
	".graphql":  "GraphQL",
	".proto":    "Protobuf",

	".sh":   "Shell",
	".bash": "Bash",
	".zsh":  "Zsh",
	".fish": "Fish",
	".ps1":  "PowerShell",
	".bat":  "Batch",
	".cmd":  "Batch",

	".env":          "Env",
	".dockerignore": "Docker",
	".gitignore":    "Git",
	".npmrc":        "NPM",
	".yarnrc":       "Yarn",

	".txt":  "Text",
	".log":  "Log",
	".csv":  "CSV",
	".tsv":  "TSV",
	".ini":  "INI",
	".cfg":  "Config",
	".conf": "Config",
}
